<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EsialLagislativoProposicoesPrioritarias extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL70632017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL35072021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL6992023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL49442020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PDC642015',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PLP2352019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 3,
                'tipo' => 2,
                'descricao' => 'PL43722012',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => '19582021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL97962018',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL63662019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL5802019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 3,
                'tipo' => 2,
                'descricao' => 'PL45462021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 3,
                'tipo' => 2,
                'descricao' => 'MSC862023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 3,
                'tipo' => 2,
                'descricao' => 'MSC852023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL62162023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL43812023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL54672023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PLP842015',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL17022021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL9762021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PLP3882014',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL832022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL276822',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL23522023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 3,
                'tipo' => 2,
                'descricao' => 'MSC41217',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 3,
                'tipo' => 2,
                'descricao' => 'MSC5162018',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL57512023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL54422020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL41352023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL15842021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL35012020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL45112021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL62162023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL6382019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PLP1082021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PLP332020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL27322022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL69692013',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL54822020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL10252022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PLP642022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PLP5042018',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL66062019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL30082020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PEC692019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL18292019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PLP3532017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PDC8632017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL29992022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL60572023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL70632017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL45302004',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL40672020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL291422',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL21592021CD',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL132020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PEC552023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL27212021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL6362023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL88212017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PLP772022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL39582019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL51782020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL43882023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 2,
                'descricao' => 'PL21482015',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 2,
                'descricao' => 'PL25282020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL21592021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL21482015',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 1,
                'descricao' => 'PL36682021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL5282020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL88892017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 1,
                'descricao' => 'PL23312022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 1,
                'descricao' => 'PL19582021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL25832020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL57862023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL57872023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL57892023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'MSC2092023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PLP1012023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL32024',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 1,
                'descricao' => 'PLC292017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL29252023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL29262023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL30252023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 1,
                'descricao' => 'PL26302020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 1,
                'tipo' => 1,
                'descricao' => 'PL23702019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'origem' => 2,
                'tipo' => 1,
                'descricao' => 'PLS23382023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ])->each(fn ($proposicao) => DB::table('esial_legislativo_proposicao_prioritarias')->insert($proposicao));
    }
}
