<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EsialUsuarioAcessoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('esial_usuario_acessos')->insert([
            [
                'esial_nivel_acesso_id' => 1,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 2,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 3,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 4,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 5,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 6,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 7,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 11,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 12,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 13,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 14,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 16,
                'esial_usuario_cadastro_id' => 1,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 1,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 2,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 3,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 4,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 5,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 6,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 7,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 11,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 12,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 13,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 14,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 16,
                'esial_usuario_cadastro_id' => 2,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 1,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 5,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 13,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 2,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 6,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 14,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 3,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 7,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 4,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 16,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 11,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 12,
                'esial_usuario_cadastro_id' => 3,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 1,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 5,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 13,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 2,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 6,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 14,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'esial_nivel_acesso_id' => 3,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 7,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 4,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 16,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 11,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 12,
                'esial_usuario_cadastro_id' => 4,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 1,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 5,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 13,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 2,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 6,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 14,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 3,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 7,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 4,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 16,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 11,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 12,
                'esial_usuario_cadastro_id' => 5,
                'responsavel' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'esial_nivel_acesso_id' => 1,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 2,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 3,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 4,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 5,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 6,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 7,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 11,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 12,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 13,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 14,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 16,
                'esial_usuario_cadastro_id' => 6,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 7,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'esial_nivel_acesso_id' => 8,
                'esial_usuario_cadastro_id' => 8,
                'responsavel' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
