<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EsialUsuarioOrgaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('esial_usuario_orgaos')->insert([
            [
                'sigla' => 'NI SEPAR',
                'nome' => 'NUCLEO DE INFORMACOES SEPAR',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'AGU',
                'nome' => 'ADVOCACIA-GERAL DA UNIAO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'ABIN',
                'nome' => 'AGENCIA BRASILEIRA DE INTELIGENCIA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'ANAC',
                'nome' => 'AGENCIA NACIONAL DE AVIACAO CIVIL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'AESP-PR',
                'nome' => 'ASSESSORIA ESPECIAL DO PRESIDENTE DA REPUBLICA',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'ANPD',
                'nome' => 'AUTORIDADE NACIONAL DE PROTECAO DE DADOS',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'BCB',
                'nome' => 'BANCO CENTRAL DO BRASIL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'CC-PR',
                'nome' => 'CASA CIVIL DA PRESIDENCIA DA REPUBLICA',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'COMAER',
                'nome' => 'COMANDO DA AERONAUTICA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'COMMAR',
                'nome' => 'COMANDO DA MARINHA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'COMEX',
                'nome' => 'COMANDO DO EXERCITO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'CGU',
                'nome' => 'CONTROLADORIA GERAL DA UNIÃO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'GSI',
                'nome' => 'GABINETE DE SEGURANCA INSTITUCIONAL',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'GPPR',
                'nome' => 'GABINETE PESSOAL DO PRESIDENTE DA REPUBLICA',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'IBAMA',
                'nome' => 'INSTITUTO BRASILEIRO DO MEIO AMBIENTE E RECURSOS RENOVÁVEIS',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MAR',
                'nome' => 'MARINHA DO BRASIL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MAPA',
                'nome' => 'MINISTERIO DA AGRICULTURA E PECUARIA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MCTI',
                'nome' => 'MINISTERIO DA CIENCIA, TECNOLOGIA E INOVACAO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MINC',
                'nome' => 'MINISTERIO DA CULTURA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MD',
                'nome' => 'MINISTERIO DA DEFESA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MEC',
                'nome' => 'MINISTERIO DA EDUCACAO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MF',
                'nome' => 'MINISTERIO DA FAZENDA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MGI',
                'nome' => 'MINISTERIO DA GESTAO E INOVACAO EM SERVICOS PUBLICOS',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MIR',
                'nome' => 'MINISTERIO DA IGUALDADE RACIAL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MIDR',
                'nome' => 'MINISTERIO DA INTEGRACAO E DESENVOLVIMENTO REGIONAL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MJSP',
                'nome' => 'MINISTERIO DA JUSTICA E SEGURANCA PUBLICA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MPA',
                'nome' => 'MINISTERIO DA PESCA E AQUICULTURA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MPS',
                'nome' => 'MINISTÉRIO DA PREVIDENCIA SOCIAL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MS',
                'nome' => 'MINISTERIO DA SAUDE',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MCID',
                'nome' => 'MINISTERIO DAS CIDADES',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MCOM',
                'nome' => 'MINISTERIO DAS COMUNICACOES',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MM',
                'nome' => 'MINISTERIO DAS MULHERES',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MRE',
                'nome' => 'MINISTERIO DAS RELACOES EXTERIORES',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MME',
                'nome' => 'MINISTÉRIO DE MINAS E ENERGIA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MDA',
                'nome' => 'MINISTERIO DO DESENVOLVIMENTO AGRARIO E AGRICULTURA FAMILIAR',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MDS',
                'nome' => 'MINISTERIO DO DESENVOLVIMENTO E ASSISTENCIA SOCIAL, FAMILIA E COMBATE A FOME',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MDIC',
                'nome' => 'MINISTERIO DO DESENVOLVIMENTO, INDUSTRIA, COMERCIO E SERVICOS',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MEMP',
                'nome' => 'MINISTERIO DO EMPREENDEDORISMO, DA MICROEMPRESA E DA EMPRESA DE PEQUENO PORTE',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MESP',
                'nome' => 'MINISTERIO DO ESPORTE',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MMA',
                'nome' => 'MINISTERIO DO MEIO AMBIENTE E MUDANCA DE CLIMA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MPO',
                'nome' => 'MINISTERIO DO PLANEJAMENTO E ORCAMENTO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MTE',
                'nome' => 'MINISTERIO DO TRABALHO E EMPREGO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MTUR',
                'nome' => 'MINISTERIO DO TURISMO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MDHC',
                'nome' => 'MINISTERIO DOS DIREITOS HUMANOS E CIDADANIA',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MPOR',
                'nome' => 'MINISTERIO DOS PORTOS E AEROPORTOS',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MPI',
                'nome' => 'MINISTERIO DOS POVOS INDIGENAS',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'MT',
                'nome' => 'MINISTERIO DOS TRANSPORTES',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'PROCGE',
                'nome' => 'PROCURADORIA-GERAL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'PPI',
                'nome' => 'PROGRAMA DE PARCERIAS DE INVESTIMENTOS',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SRF',
                'nome' => 'SECRETARIA DA RECEITA FEDERAL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SADEN',
                'nome' => 'SECRETARIA DE ASSESSORAMENTO DA DEFESA NACIONAL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SECOM',
                'nome' => 'SECRETARIA DE COMUNICACAO SOCIAL',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SRI',
                'nome' => 'SECRETARIA DE RELAÇÕES INSTITUCIONAIS DA PRESIDÊNCIA DA REPÚBLICA',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SAG',
                'nome' => 'SECRETARIA ESPECIAL DE ANALISE GOVERNAMENTAL',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SAM',
                'nome' => 'SECRETARIA ESPECIAL DE ARTICULACAO E MONITORAMENTO',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SEAE-PR',
                'nome' => 'SECRETARIA ESPECIAL DE ASSUNTOS ESTRATEGICOS',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SAF',
                'nome' => 'SECRETARIA ESPECIAL DE ASSUNTOS FEDERATIVOS',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SAJ',
                'nome' => 'SECRETARIA ESPECIAL PARA ASSUNTOS JURIDICOS',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SEPNIV',
                'nome' => 'SECRETARIA EXECUTIVA DO PROGRAMA NACIONAL DE INCENTIVO AO VOLUNTARIADO (PATRIA VOLUNTARIA)',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SGSNJ',
                'nome' => 'SECRETARIA GERAL - SECRETARIA NACIONAL DA JUVENTUDE',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'SG',
                'nome' => 'SECRETARIA GERAL DA PRESIDENCIA DA REPUBLICA',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'TCU',
                'nome' => 'TRIBUNAL DE CONTAS DA UNIAO',
                'tipo' => 'EXTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'sigla' => 'VPR',
                'nome' => 'VICE-PRESIDENCIA DA REPUBLICA',
                'tipo' => 'INTERNO',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
